# Site settings
title: Yixing Studies Working Papers
description: Open access repository for Yixing teapot research
url: "https://yixingstudies.github.io"
baseurl: "/yixing-studies"

# Organization Info
organization: "TEA ACROSS BORDERS LLC"
organization_type: "Publisher"
established: "2025"

# Build settings
markdown: kramdown
theme: minima

# Contact
email: papers@yixingstudies.org
editor_email: editor@yixingstudies.org

# Footer
footer_text: "© 2025 TEA ACROSS BORDERS LLC. All papers remain property of their authors."