# Site settings
title: Yixing Studies Working Papers
description: Open access repository for Yixing teapot research
url: "https://yixingstudies.org"
baseurl: ""

# Organization Info
organization: "TEA ACROSS BORDERS LLC"
organization_type: "Publisher"
established: "2025"

# Build settings
markdown: kramdown
theme: minima

# Contact
email: admin@yixingstudies.org
editor_email: admin@yixingstudies.org
# Footer
footer_text: "© 2025 TEA ACROSS BORDERS LLC. All papers remain property of their authors."
